# Generated by Django 3.1 on 2020-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('course', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
