# Generated by Django 3.1 on 2020-08-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Orderss',
        ),
    ]
