# Generated by Django 3.1 on 2020-08-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200822_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderss',
            new_name='Orders',
        ),
    ]
