# Generated by Django 3.1 on 2020-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200822_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
    ]
