# Generated by Django 3.1 on 2020-08-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200822_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
